language: java
script:
  - #echo "=== set ==="
  - #set
  - #echo "=== export ==="
  - #export
  - mvn -Pci -Dbuild.number="${TRAVIS_BUILD_NUMBER}" -Dbuild.branch="${TRAVIS_BRANCH}" clean verify -f com.blackdogit.connectiq.monkeyc.root/pom.xml
install: true
notifications:
  email:
    recipients:
    - tonny.madsen@blackdogit.com
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_failure:
  - echo "=== SUREFIRE REPORTS ==="
  - for F in com.blackdogit.connectiq.*/target/surefire-reports/*.txt; do echo $F && cat $F && echo; done
  - echo "=== *log* ==="
  - find . -type f -name "*log*" | while read f; do echo ">> $f"; cat "$f"; done
after_success:
  - bash  ./releaseRepository.sh
env:
  global:
    secure: LZgkK1L6/gIDbGM4o2YIUWK0VpbjMA9KUGk77IO7jNqeRKjuFa8I1De92+LtGcTcALqThRRAUzgB68XG4LE3Eo9i9PUEwzSjQIiTWdtZlErCz368SljZz2ocIHhd6vIeOVkElTV8S9LVaOlKBmji3HhcaIfK6KUZR43Pgy4qc7Y=
