/*
 * generated by Xtext
 */
package com.blackdogit.connectiq;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MonkeyCRuntimeModule extends com.blackdogit.connectiq.AbstractMonkeyCRuntimeModule {

}
