/*
* generated by Xtext
*/
package com.blackdogit.connectiq;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MonkeyCStandaloneSetup extends MonkeyCStandaloneSetupGenerated{

	public static void doSetup() {
		new MonkeyCStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

