/*
 * generated by Xtext
 */
package com.blackdogit.connectiq.ui.contentassist

import com.blackdogit.connectiq.ui.contentassist.AbstractMonkeyCProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MonkeyCProposalProvider extends AbstractMonkeyCProposalProvider {
}
