/*
 * generated by Xtext
 */
package com.blackdogit.connectiq.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MonkeyCUiModule extends com.blackdogit.connectiq.ui.AbstractMonkeyCUiModule {
	public MonkeyCUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
